FROM node:latest

ARG TELEGRAM_TOKEN
ENV TELEGRAM_TOKEN=$TELEGRAM_TOKEN

ARG ACCESS_KEY_ID
ENV ACCESS_KEY_ID=$ACCESS_KEY_ID

ARG SECRET_ACCESS_KEY
ENV SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY

RUN mkdir -p /app
WORKDIR /app
COPY . /app
RUN npm install
CMD [ "npm", "start" ]
